insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Kipling', 339, 2, 16, '140-093', 'Río Blanco', 'Nicaragua', 8);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Mosinee', 890, 9, 115, '4660-059', 'Tarbes', 'France', 29);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Lukken', 546, 5, 97, '4660-059', 'Stockholm', 'Sweden', 28);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Harper', 848, 1, 186, '399-260', 'Utrecht (stad)', 'Netherlands', 27);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Jenifer', 168, 9, 169, '4660-059', 'Lysá nad Labem', 'Czech Republic', 25);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Memorial', 979, 4, 195, '821-80', 'Kamenica', 'Kosovo', 5);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Surrey', 840, 8, 56, '922-751', 'Gaoshi', 'China', 28);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Corben', 451, 3, 147, '297-680', 'Qelëz', 'Albania', 3);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Walton', 794, 6, 46, '634-544', 'Stoney Ground', 'Anguilla', 15);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Ilene', 236, 10, 47, '4540-243', 'Ciengang', 'Indonesia', 1);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Trailsway', 918, 6, 92, '634-544', 'Huishangang', 'China', 16);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Westridge', 154, 4, 19, '501-0531', 'Kamiiso', 'Japan', 26);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cottonwood', 486, 4, 132, '757-54', 'Uppsala', 'Sweden', 21);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Mosinee', 541, 6, 17, '15-600', 'Alīābad', 'Pakistan', 18);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Orin', 713, 3, 94, '687-200', 'Dul’durga', 'Russia', 10);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Graceland', 152, 10, 28, '236-809', 'Leiden', 'Netherlands', 8);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cottonwood', 373, 4, 170, '58884-000', 'Zhong’an', 'China', 7);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Vidon', 34, 10, 59, '234-050', 'Dongjin', 'China', 23);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Huxley', 978, 2, 98, '3931-94', 'Chongkan', 'China', 9);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Debs', 231, 2, 6, '532-325', 'Sukoreno', 'Indonesia', 11);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cody', 841, 7, 184, '7344-32', 'Pasolapida', 'Indonesia', 19);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Sunbrook', 994, 7, 74, '487-967', 'Jinshan', 'China', 15);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Rusk', 120, 8, 164, '3927-573', 'Gadžin Han', 'Serbia', 18);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Swallow', 450, 9, 20, '6340-000', 'Icó', 'Brazil', 27);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Hayes', 344, 10, 98, '301-735', 'Strel''na', 'Russia', 12);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('East', 941, 4, 44, '0587-32', 'Yuanquan', 'China', 27);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cardinal', 486, 10, 161, '47-203', 'Bellavista', 'Mexico', 25);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Lillian', 366, 4, 120, '664-705', 'Lupon', 'Philippines', 4);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Lillian', 307, 2, 55, '582-8673', 'Abakaliki', 'Nigeria', , 3);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Florence', 837, 4, 16, '8573-857', 'Sinfra', 'Ivory Coast', 2);
