insert into data.subcategories (subcategory, category_id) values ('Baseball top', 1);
insert into data.subcategories (subcategory, category_id) values ('Bolero', 4);
insert into data.subcategories (subcategory, category_id) values ('Bodysuit', 3);
insert into data.subcategories (subcategory, category_id) values ('Camisole', 1);
insert into data.subcategories (subcategory, category_id) values ('Cardigan', 4);
insert into data.subcategories (subcategory, category_id) values ('Corset', 1);
insert into data.subcategories (subcategory, category_id) values ('Cowl neck top', 1);
insert into data.subcategories (subcategory, category_id) values ('Crop top', 1);
insert into data.subcategories (subcategory, category_id) values ('Duster', 4);
insert into data.subcategories (subcategory, category_id) values ('Halter top', 1);
insert into data.subcategories (subcategory, category_id) values ('Bell bottoms', 2);
insert into data.subcategories (subcategory, category_id) values ('Capris', 2);
insert into data.subcategories (subcategory, category_id) values ('Cargo pants', 2);
insert into data.subcategories (subcategory, category_id) values ('Jeans', 2);
insert into data.subcategories (subcategory, category_id) values ('Handbag', 7);
insert into data.subcategories (subcategory, category_id) values ('Bandana', 7);
insert into data.subcategories (subcategory, category_id) values ('Leggings', 2);
insert into data.subcategories (subcategory, category_id) values ('Slacks', 2);
insert into data.subcategories (subcategory, category_id) values ('Caftan', 3);
insert into data.subcategories (subcategory, category_id) values ('Halter neck dress', 3);
insert into data.subcategories (subcategory, category_id) values ('Midi dress', 3);
insert into data.subcategories (subcategory, category_id) values ('Blazer', 4);
insert into data.subcategories (subcategory, category_id) values ('Bra', 5);
insert into data.subcategories (subcategory, category_id) values ('Chemise', 5);
insert into data.subcategories (subcategory, category_id) values ('Stockings', 5);
insert into data.subcategories (subcategory, category_id) values ('Boxer shorts', 5);
insert into data.subcategories (subcategory, category_id) values ('Briefs', 5);
insert into data.subcategories (subcategory, category_id) values ('Trainers', 6);
insert into data.subcategories (subcategory, category_id) values ('Hi-top sneakers', 6);
insert into data.subcategories (subcategory, category_id) values ('Backpack', 7);
