insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Ibuprofen', 7, 22, 28, '$38.05', 68, 25);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Zep Provisions Pot and Pan Premium', 17, 23, 26, '$83.51', 35, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Naproxen Sodium', 26, 5, 25, '$56.08', 41, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Norco', 20, 14, 14, '$33.80', 86, 12);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Ladies Speed Stick', 15, 18, 20, '$66.46', 95, 21);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Anti-Bacterial Hand', 9, 21, 28, '$83.09', 12, 18);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Atenolol', 17, 30, 16, '$60.12', 52, 26);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Carac', 7, 16, 29, '$57.45', 17, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Dandruff', 19, 30, 8, '$85.51', 79, 29);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('zzz sleep', 15, 27, 3, '$55.18', 84, 14);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Sage Mixture', 19, 15, 6, '$88.94', 94, 29);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Warfarin Sodium', 13, 19, 14, '$90.75', 67, 22);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Quetiapine fumarate', 29, 5, 29, '$7.05', 20, 28);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Assured Vaporizing Chest Rub', 11, 30, 12, '$55.65', 64, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('L-Methylfolate Calcium', 15, 15, 25, '$42.71', 21, 11);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Deb Med Antimicrobial Foaming Hand Wash Cucumber Aloe', 8, 9, 26, '$58.62', 15, 1);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Naproxen Sodium', 8, 29, 14, '$88.12', 79, 24);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Irbesartan and Hydrochlorothiazide', 16, 8, 27, '$63.11', 58, 24);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Thyropar', 4, 20, 25, '$58.47', 39, 26);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Time Frame Future Resist Foundation Broad Spectrum SPF 20', 15, 8, 25, '$23.88', 44, 9);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('H-Balm Control', 10, 9, 2, '$86.43', 30, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Treatment Set TS346964', 4, 6, 21, '$67.90', 84, 25);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Tolnaftate', 2, 22, 26, '$60.47', 1, 1);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Topiramate', 9, 1, 4, '$83.18', 24, 20);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Xenazine', 6, 22, 29, '$31.78', 1, 27);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Ketoconazole', 17, 5, 16, '$95.25', 17, 1);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Glandulae suprarenales 6 Special Order', 23, 15, 17, '$26.09', 92, 3);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Topcare Day Time Nite Time Cold and Flu Relief', 17, 18, 14, '$58.84', 37, 2);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('LEVOFLOXACIN', 22, 1, 30, '$18.45', 92, 23);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Exelon', 9, 21, 12, '$6.35', 2, 21);
