insert into data.brand (brand) values ('Nike');
insert into data.brand (brand) values ('Louis Vuitton');
insert into data.brand (brand) values ('Gucci');
insert into data.brand (brand) values ('Hermes');
insert into data.brand (brand) values ('Adidas');
insert into data.brand (brand) values ('Zara');
insert into data.brand (brand) values ('H&M');
insert into data.brand (brand) values ('UNIQLO');
insert into data.brand (brand) values ('Tiffany & Co.');
insert into data.brand (brand) values ('COACH');
insert into data.brand (brand) values ('Chow Tai Fook');
insert into data.brand (brand) values ('Burberry');
insert into data.brand (brand) values ('Anta');
insert into data.brand (brand) values ('Ray-Ban');
insert into data.brand (brand) values ('Puma');
insert into data.brand (brand) values ('The North Face');
insert into data.brand (brand) values ('Lululemon');
insert into data.brand (brand) values ('Ralph Lauren');
insert into data.brand (brand) values ('Victoria s Secret');
insert into data.brand (brand) values ('Omega');
insert into data.brand (brand) values ('Levis');
insert into data.brand (brand) values ('Moncler');
insert into data.brand (brand) values ('Fila');
insert into data.brand (brand) values ('Prada');
insert into data.brand (brand) values ('Armani');
insert into data.brand (brand) values ('Bulgari');
insert into data.brand (brand) values ('Tommy Hilfiger');
insert into data.brand (brand) values ('Michael Kors');
insert into data.brand (brand) values ('Calvin Klein');
insert into data.brand (brand) values ('Boss');
