insert into data.categories (category) values ('Tops');
insert into data.categories (category) values ('Bottoms');
insert into data.categories (category) values ('One piece');
insert into data.categories (category) values ('Outerwear');
insert into data.categories (category) values ('Intimates');
insert into data.categories (category) values ('Footwear');
insert into data.categories (category) values ('Accessories');
insert into data.categories (category) values ('Other');
insert into data.subcategories (subcategory, category_id) values ('Baseball top', 1);
insert into data.subcategories (subcategory, category_id) values ('Bolero', 4);
insert into data.subcategories (subcategory, category_id) values ('Bodysuit', 3);
insert into data.subcategories (subcategory, category_id) values ('Camisole', 1);
insert into data.subcategories (subcategory, category_id) values ('Cardigan', 4);
insert into data.subcategories (subcategory, category_id) values ('Corset', 1);
insert into data.subcategories (subcategory, category_id) values ('Cowl neck top', 1);
insert into data.subcategories (subcategory, category_id) values ('Crop top', 1);
insert into data.subcategories (subcategory, category_id) values ('Duster', 4);
insert into data.subcategories (subcategory, category_id) values ('Halter top', 1);
insert into data.subcategories (subcategory, category_id) values ('Bell bottoms', 2);
insert into data.subcategories (subcategory, category_id) values ('Capris', 2);
insert into data.subcategories (subcategory, category_id) values ('Cargo pants', 2);
insert into data.subcategories (subcategory, category_id) values ('Jeans', 2);
insert into data.subcategories (subcategory, category_id) values ('Handbag', 7);
insert into data.subcategories (subcategory, category_id) values ('Bandana', 7);
insert into data.subcategories (subcategory, category_id) values ('Leggings', 2);
insert into data.subcategories (subcategory, category_id) values ('Slacks', 2);
insert into data.subcategories (subcategory, category_id) values ('Caftan', 3);
insert into data.subcategories (subcategory, category_id) values ('Halter neck dress', 3);
insert into data.subcategories (subcategory, category_id) values ('Midi dress', 3);
insert into data.subcategories (subcategory, category_id) values ('Blazer', 4);
insert into data.subcategories (subcategory, category_id) values ('Bra', 5);
insert into data.subcategories (subcategory, category_id) values ('Chemise', 5);
insert into data.subcategories (subcategory, category_id) values ('Stockings', 5);
insert into data.subcategories (subcategory, category_id) values ('Boxer shorts', 5);
insert into data.subcategories (subcategory, category_id) values ('Briefs', 5);
insert into data.subcategories (subcategory, category_id) values ('Trainers', 6);
insert into data.subcategories (subcategory, category_id) values ('Hi-top sneakers', 6);
insert into data.subcategories (subcategory, category_id) values ('Backpack', 7);
insert into data.gender (gender) values ('Combat helicopter');
insert into data.gender (gender) values ('Male');
insert into data.gender (gender) values ('Polar bear');
insert into data.gender (gender) values ('Neither');
insert into data.gender (gender) values ('Non-binary');
insert into data.gender (gender) values ('Neurogender');
insert into data.gender (gender) values ('Trans female');
insert into data.gender (gender) values ('Trans male');
insert into data.gender (gender) values ('Tumtum');
insert into data.gender (gender) values ('Agender');
insert into data.gender (gender) values ('Demiflux');
insert into data.gender (gender) values ('Dual gender');
insert into data.gender (gender) values ('General Dynamics F-16 Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics F-16IN Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics F-16N Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics F-16V Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics QF-16 Fighting Falcon');
insert into data.gender (gender) values ('Endosex');
insert into data.gender (gender) values ('Nuclear warhead');
insert into data.gender (gender) values ('Air-to-air missile');
insert into data.gender (gender) values ('Tank');
insert into data.gender (gender) values ('Vakasalewalewa');
insert into data.gender (gender) values ('X-gender');
insert into data.gender (gender) values ('Waria');
insert into data.gender (gender) values ('Cat');
insert into data.gender (gender) values ('Queer');
insert into data.gender (gender) values ('MTF');
insert into data.gender (gender) values ('Maverique');
insert into data.gender (gender) values ('Neutrois');
insert into data.gender (gender) values ('Female');
insert into data.size (size) values ('XS');
insert into data.size (size) values ('S');
insert into data.size (size) values ('M');
insert into data.size (size) values ('L');
insert into data.size (size) values ('XL');
insert into data.size (size) values ('XXL');
insert into data.size (size) values ('3XL');
insert into data.size (size) values ('29');
insert into data.size (size) values ('30');
insert into data.size (size) values ('31');
insert into data.size (size) values ('32');
insert into data.size (size) values ('33');
insert into data.size (size) values ('34');
insert into data.size (size) values ('35');
insert into data.size (size) values ('36');
insert into data.size (size) values ('37');
insert into data.size (size) values ('38');
insert into data.size (size) values ('39');
insert into data.size (size) values ('40');
insert into data.size (size) values ('41');
insert into data.size (size) values ('42');
insert into data.size (size) values ('43');
insert into data.size (size) values ('44');
insert into data.size (size) values ('45');
insert into data.size (size) values ('46');
insert into data.size (size) values ('47');
insert into data.size (size) values ('48');
insert into data.size (size) values ('49');
insert into data.size (size) values ('50');
insert into data.size (size) values ('51');
insert into data.brand (brand) values ('Nike');
insert into data.brand (brand) values ('Louis Vuitton');
insert into data.brand (brand) values ('Gucci');
insert into data.brand (brand) values ('Hermes');
insert into data.brand (brand) values ('Adidas');
insert into data.brand (brand) values ('Zara');
insert into data.brand (brand) values ('H&M');
insert into data.brand (brand) values ('UNIQLO');
insert into data.brand (brand) values ('Tiffany & Co.');
insert into data.brand (brand) values ('COACH');
insert into data.brand (brand) values ('Chow Tai Fook');
insert into data.brand (brand) values ('Burberry');
insert into data.brand (brand) values ('Anta');
insert into data.brand (brand) values ('Ray-Ban');
insert into data.brand (brand) values ('Puma');
insert into data.brand (brand) values ('The North Face');
insert into data.brand (brand) values ('Lululemon');
insert into data.brand (brand) values ('Ralph Lauren');
insert into data.brand (brand) values ('Victoria s Secret');
insert into data.brand (brand) values ('Omega');
insert into data.brand (brand) values ('Levis');
insert into data.brand (brand) values ('Moncler');
insert into data.brand (brand) values ('Fila');
insert into data.brand (brand) values ('Prada');
insert into data.brand (brand) values ('Armani');
insert into data.brand (brand) values ('Bulgari');
insert into data.brand (brand) values ('Tommy Hilfiger');
insert into data.brand (brand) values ('Michael Kors');
insert into data.brand (brand) values ('Calvin Klein');
insert into data.brand (brand) values ('Boss');
insert into data.payments (payment_method) values ('Cash');
insert into data.payments (payment_method) values ('Card');
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Tanny', 'Matthessen', 'tmatthessen0@diigo.com', '445-389-2263', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Steffie', 'Gaze', 'sgaze1@eventbrite.com', '335-205-7625', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Thekla', 'Everley', 'teverley2@foxnews.com', '855-241-7133', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Udall', 'Werrett', 'uwerrett3@accuweather.com', '472-624-9990', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Lenard', 'Ordemann', 'lordemann4@zdnet.com', '842-893-4515', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Pietrek', 'Johnes', 'pjohnes5@japanpost.jp', '168-566-0461', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Zack', 'Mannock', 'zmannock6@twitpic.com', '316-652-9875', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Evelin', 'Tallis', 'etallis7@so-net.ne.jp', '230-614-0654', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Lowrance', 'Tarbatt', 'ltarbatt8@mozilla.com', '290-846-7857', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Clemmie', 'Bulled', 'cbulled9@privacy.gov.au', '195-656-2261', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Constantia', 'Haughey', 'chaugheya@tumblr.com', '707-466-6197', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Sherie', 'Fredson', 'sfredsonb@amazon.com', '483-103-4117', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Gerry', 'Ortiger', 'gortigerc@privacy.gov.au', '232-663-4229', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Nancey', 'Piecha', 'npiechad@upenn.edu', '512-372-4643', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Prince', 'McConnachie', 'pmcconnachiee@opensource.org', '316-244-6551', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Adel', 'Pavie', 'apavief@nih.gov', '234-931-6612', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Betsy', 'Twigger', 'btwiggerg@narod.ru', '513-563-9519', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Enrique', 'Jays', 'ejaysh@google.ru', '638-878-0589', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Johannes', 'Hussy', 'jhussyi@ycombinator.com', '987-574-6602', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Marleen', 'Mulmuray', 'mmulmurayj@mozilla.com', '240-594-1609', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Meridith', 'Fullagar', 'mfullagark@printfriendly.com', '440-829-2699', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Bradly', 'Showell', 'bshowelll@nydailynews.com', '656-717-4488', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Elly', 'Castagnaro', 'ecastagnarom@com.com', '946-691-4425', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Clemmie', 'Looker', 'clookern@youtu.be', '645-417-0137', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Marie-jeanne', 'Mikalski', 'mmikalskio@sakura.ne.jp', '571-522-1172', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Sayre', 'Rickerd', 'srickerdp@shinystat.com', '263-696-2245', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Felizio', 'Bellenie', 'fbellenieq@people.com.cn', '787-731-8943', 2);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Tatiania', 'Columbell', 'tcolumbellr@myspace.com', '747-695-8401', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Karrah', 'Kubica', 'kkubicas@prweb.com', '202-654-8787', 1);
insert into data.user (name, surname, email, phone, preferred_payment_method_id) values ('Rudolfo', 'Scudamore', 'rscudamoret@boston.com', '419-169-0843', 2);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Kipling', 339, 2, 16, '140-093', 'Río Blanco', 'Nicaragua', 8);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Mosinee', 890, 9, 115, '4660-059', 'Tarbes', 'France', 29);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Lukken', 546, 5, 97, '4660-059', 'Stockholm', 'Sweden', 28);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Harper', 848, 1, 186, '399-260', 'Utrecht (stad)', 'Netherlands', 27);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Jenifer', 168, 9, 169, '4660-059', 'Lysá nad Labem', 'Czech Republic', 25);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Memorial', 979, 4, 195, '821-80', 'Kamenica', 'Kosovo', 5);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Surrey', 840, 8, 56, '922-751', 'Gaoshi', 'China', 28);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Corben', 451, 3, 147, '297-680', 'Qelëz', 'Albania', 3);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Walton', 794, 6, 46, '634-544', 'Stoney Ground', 'Anguilla', 15);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Ilene', 236, 10, 47, '4540-243', 'Ciengang', 'Indonesia', 1);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Trailsway', 918, 6, 92, '634-544', 'Huishangang', 'China', 16);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Westridge', 154, 4, 19, '501-0531', 'Kamiiso', 'Japan', 26);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cottonwood', 486, 4, 132, '757-54', 'Uppsala', 'Sweden', 21);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Mosinee', 541, 6, 17, '15-600', 'Alīābad', 'Pakistan', 18);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Orin', 713, 3, 94, '687-200', 'Dul’durga', 'Russia', 10);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Graceland', 152, 10, 28, '236-809', 'Leiden', 'Netherlands', 8);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cottonwood', 373, 4, 170, '58884-000', 'Zhong’an', 'China', 7);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Vidon', 34, 10, 59, '234-050', 'Dongjin', 'China', 23);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Huxley', 978, 2, 98, '3931-94', 'Chongkan', 'China', 9);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Debs', 231, 2, 6, '532-325', 'Sukoreno', 'Indonesia', 11);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cody', 841, 7, 184, '7344-32', 'Pasolapida', 'Indonesia', 19);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Sunbrook', 994, 7, 74, '487-967', 'Jinshan', 'China', 15);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Rusk', 120, 8, 164, '3927-573', 'Gadžin Han', 'Serbia', 18);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Swallow', 450, 9, 20, '6340-000', 'Icó', 'Brazil', 27);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Hayes', 344, 10, 98, '301-735', 'Strel''na', 'Russia', 12);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('East', 941, 4, 44, '0587-32', 'Yuanquan', 'China', 27);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Cardinal', 486, 10, 161, '47-203', 'Bellavista', 'Mexico', 25);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Lillian', 366, 4, 120, '664-705', 'Lupon', 'Philippines', 4);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Lillian', 307, 2, 55, '582-8673', 'Abakaliki', 'Nigeria', 3);
insert into data.address (street, building_number, frame_number, apartment_number, zip_code, city, country, user_id) values ('Florence', 837, 4, 16, '8573-857', 'Sinfra', 'Ivory Coast', 2);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Ibuprofen', 7, 22, 28, '$38.05', 68, 25);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Zep Provisions Pot and Pan Premium', 17, 23, 26, '$83.51', 35, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Naproxen Sodium', 26, 5, 25, '$56.08', 41, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Norco', 20, 14, 14, '$33.80', 86, 12);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Ladies Speed Stick', 15, 18, 20, '$66.46', 95, 21);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Anti-Bacterial Hand', 9, 21, 28, '$83.09', 12, 18);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Atenolol', 17, 30, 16, '$60.12', 52, 26);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Carac', 7, 16, 29, '$57.45', 17, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Dandruff', 19, 30, 8, '$85.51', 79, 29);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('zzz sleep', 15, 27, 3, '$55.18', 84, 14);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Sage Mixture', 19, 15, 6, '$88.94', 94, 29);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Warfarin Sodium', 13, 19, 14, '$90.75', 67, 22);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Quetiapine fumarate', 29, 5, 29, '$7.05', 20, 28);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Assured Vaporizing Chest Rub', 11, 30, 12, '$55.65', 64, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('L-Methylfolate Calcium', 15, 15, 25, '$42.71', 21, 11);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Deb Med Antimicrobial Foaming Hand Wash Cucumber Aloe', 8, 9, 26, '$58.62', 15, 1);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Naproxen Sodium', 8, 29, 14, '$88.12', 79, 24);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Irbesartan and Hydrochlorothiazide', 16, 8, 27, '$63.11', 58, 24);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Thyropar', 4, 20, 25, '$58.47', 39, 26);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Time Frame Future Resist Foundation Broad Spectrum SPF 20', 15, 8, 25, '$23.88', 44, 9);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('H-Balm Control', 10, 9, 2, '$86.43', 30, 16);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Treatment Set TS346964', 4, 6, 21, '$67.90', 84, 25);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Tolnaftate', 2, 22, 26, '$60.47', 1, 1);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Topiramate', 9, 1, 4, '$83.18', 24, 20);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Xenazine', 6, 22, 29, '$31.78', 1, 27);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Ketoconazole', 17, 5, 16, '$95.25', 17, 1);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Glandulae suprarenales 6 Special Order', 23, 15, 17, '$26.09', 92, 3);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Topcare Day Time Nite Time Cold and Flu Relief', 17, 18, 14, '$58.84', 37, 2);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('LEVOFLOXACIN', 22, 1, 30, '$18.45', 92, 23);
insert into data.product (name, brand_id, size_id, gender_id, price, quantity, subcategory_id) values ('Exelon', 9, 21, 12, '$6.35', 2, 21);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (21, 4, 7, 28, '$267.89', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (2, 21, 9, 11, '$284.26', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (18, 24, 2, 2, '$157.17', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (2, 27, 4, 15, '$258.64', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (6, 20, 6, 26, '$706.80', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (18, 1, 8, 15, '$822.57', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (6, 23, 9, 12, '$679.97', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (14, 17, 1, 16, '$449.87', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (19, 20, 2, 13, '$910.57', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (20, 27, 3, 6, '$827.44', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (9, 4, 2, 15, '$634.37', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (7, 24, 4, 29, '$745.33', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (26, 12, 2, 10, '$672.23', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (25, 19, 5, 8, '$619.60', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (11, 9, 9, 22, '$404.67', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (23, 16, 5, 12, '$475.95', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (5, 4, 2, 6, '$820.73', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (16, 16, 9, 9, '$786.93', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (28, 26, 2, 18, '$714.00', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (24, 19, 3, 11, '$348.71', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (21, 30, 9, 27, '$597.32', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (11, 5, 2, 18, '$851.16', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (7, 11, 2, 23, '$220.62', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (18, 4, 3, 3, '$631.58', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (2, 28, 9, 18, '$337.05', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (6, 5, 7, 12, '$944.04', 2);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (25, 2, 6, 20, '$486.68', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (25, 5, 8, 4, '$418.32', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (26, 24, 10, 13, '$456.36', 1);
insert into data.order (user_id, product_id, pieces, address_id, amount, payment_type_id) values (6, 3, 1, 26, '$902.30', 2);
