insert into data.gender (gender) values ('Combat helicopter');
insert into data.gender (gender) values ('Male');
insert into data.gender (gender) values ('Polar bear');
insert into data.gender (gender) values ('Neither');
insert into data.gender (gender) values ('Non-binary');
insert into data.gender (gender) values ('Neurogender');
insert into data.gender (gender) values ('Trans female');
insert into data.gender (gender) values ('Trans male');
insert into data.gender (gender) values ('Tumtum');
insert into data.gender (gender) values ('Agender');
insert into data.gender (gender) values ('Demiflux');
insert into data.gender (gender) values ('Dual gender');
insert into data.gender (gender) values ('General Dynamics F-16 Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics F-16IN Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics F-16N Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics F-16V Fighting Falcon');
insert into data.gender (gender) values ('General Dynamics QF-16 Fighting Falcon');
insert into data.gender (gender) values ('Endosex');
insert into data.gender (gender) values ('Nuclear warhead');
insert into data.gender (gender) values ('Air-to-air missile');
insert into data.gender (gender) values ('Tank');
insert into data.gender (gender) values ('Vakasalewalewa');
insert into data.gender (gender) values ('X-gender');
insert into data.gender (gender) values ('Waria');
insert into data.gender (gender) values ('Cat');
insert into data.gender (gender) values ('Queer');
insert into data.gender (gender) values ('MTF');
insert into data.gender (gender) values ('Maverique');
insert into data.gender (gender) values ('Neutrois');
insert into data.gender (gender) values ('Female');
